openapi: 3.0.1
info:
  title: Company API
  description: API REST para la gestión de empleados.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Servicio dedicado a la creacion, modificacion, obtencion y eliminacion de empleados

paths:
  /employees/{id}:
    get:
      summary: Obtener empleado por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID del empleado
      responses:
        '200':
          description: Empleado encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
        '404':
          description: Empleado no encontrado

    patch:
      summary: Actualizar parcialmente un empleado
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Empleado actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'

    delete:
      summary: Eliminar empleado por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Empleado eliminado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
        '404':
          description: Empleado no encontrado

  /employees:
    get:
      summary: Obtener todos los empleados
      responses:
        '200':
          description: Lista de empleados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmployeeResponse'

  /employees/createEmployee:
    post:
      summary: Crear nuevo empleado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeRequest'
      responses:
        '201':
          description: Empleado creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
        '400':
          description: Datos inválidos

components:
  schemas:
    Gender:
      type: string
      enum: [MALE, FEMALE]

    EmployeeRequest:
      type: object
      required:
        - firstName
        - midName
        - fatherLastName
        - motherLastName
        - age
        - gender
        - birthdate
        - position
      properties:
        firstName:
          type: string
        midName:
          type: string
        fatherLastName:
          type: string
        motherLastName:
          type: string
        age:
          type: integer
          minimum: 18
          maximum: 120
        gender:
          $ref: '#/components/schemas/Gender'
        birthdate:
          type: string
          format: date
        position:
          type: string

    EmployeeResponse:
      allOf:
        - $ref: '#/components/schemas/EmployeeRequest'
        - type: object
          properties:
            id:
              type: integer

    DeleteResponse:
      type: object
      properties:
        message:
          type: string
